export const COMMON_ACTIONS = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR'
}

export const SIDEBAR_ACTIONS = {
  SET_ACTIVE_ITEM: 'SET_ACTIVE_ITEM'
}

export const FILE_ACTIONS = {
  GET_FILE_UPLOAD_URL: 'GET_FILE_UPLOAD_URL',
  SAVE_FILE_TO_S3: ' SAVE_FILE_TO_S3',
  SAVE_FILE_TO_QUE: 'SAVE_FILE_TO_QUE',
  DOWNLOAD_FILE: 'DOWNLOAD_FILE',
  DELETE_FILE: 'DELETE_FILE',
  SESSION_DELETE: 'SESSION_DELETE'
}
export const STATUS_ACTIONS = {
  GET_GOAL_STATUS_LIST: 'GET_GOAL_STATUS_LIST',
  GET_ENGAGEMENT_STATUS_LIST: 'GET_ENGAGEMENT_STATUS_LIST',
  GET_SESSION_STATUS_LIST: 'GET_SESSION_STATUS_LIST'
}

export const ALERT_ACTIONS = {
  TRIGGER_ALERT_MESSAGE: 'TRIGGER_ALERT_MESSAGE',
  CLOSE_ALERT_MESSAGE: 'CLOSE_ALERT_MESSAGE',
  REMOVE_ALERT_MESSAGE: 'REMOVE_ALERT_MESSAGE'
}

export const AUTH_ACTION_TYPE = {
  AUTHORIZE_USER: 'AUTHORIZE_USER',
  FETCH_AUTHORIZE_USER: 'FETCH_AUTHORIZE_USER',
  FETCH_AUTHORIZE_USER_PERMISSION: 'FETCH_AUTHORIZE_USER_PERMISSION',
  LOGOUT: 'LOGOUT'
}

export const USERS_ACTION_TYPE = {
  GET_ALL_COACHES: 'GET_ALL_COACHES'
}

export const DASHBOARD_ACTION_TYPE = {
  GET_COACHEE_STATS: 'GET_COACHEE_STATS',
  GET_COACHEE_GOAL_SUMMARY: 'GET_COACHEE_GOAL_SUMMARY',
  GET_COACHEE_SESSION_SUMMARY: 'GET_COACHEE_SESSION_SUMMARY',
  GET_RECENT_ENGAGEMENTS_AS_COACHEE: 'GET_RECENT_ENGAGEMENTS_AS_COACHEE',
  GET_COACH_STATS: 'GET_COACH_STATS',
  GET_COACH_GOAL_SUMMARY: 'GET_COACH_GOAL_SUMMARY',
  GET_COACH_SESSION_SUMMARY: 'GET_COACH_SESSION_SUMMARY',
  GET_RECENT_ENGAGEMENTS_AS_COACH: 'GET_RECENT_ENGAGEMENTS_AS_COACH',
  GET_SUPERVISOR_STATS: 'GET_SUPERVISOR_STATS'
}

export const PROFILE_ACTIONS = {
  MAKE_ADMIN: 'MAKE_ADMIN',
  OPEN_MODAL: 'OPEN_MODAL'
}

// ---------------------NEW Ursaleo  Actions above need to be deleted

export const CLIENT_ACTIONS = {
  CREATE_CLIENT: 'CREATE_CLIENT',
  GET_SELECTED_CLIENT_DETAILS: 'GET_SELECTED_CLIENT_DETAILS',
  CLEAR_SELECTED_CLIENT_DETAILS: 'CLEAR_SELECTED_CLIENT_DETAILS'
}
export const USER_ACTIONS = {
  CREATE_USER: 'CREATE_USER',
  GET_CLIENT_ADMIN_LIST: 'GET_CLIENT_ADMIN_LIST',
  STORE_USER: 'STORE_USER'
}

export const ENTITLEMENT_ACTIONS = {
  GET_MY_ENTITLEMENT: 'GET_MY_ENTITLEMENT',
  GET_ALL_CLIENTS: 'GET_ALL_CLIENTS',
  ADD__ENTITLEMENT_BULK: 'ADD__ENTITLEMENT_BULK'

}

export const TWIN_ACTIONS = {
  GET_ALL_TWINS: 'GET_ALL_TWINS',
  GET_ALL_TWINS_LIST: 'GET_ALL_TWINS_LIST',
  DOWNLOAD_TWIN: 'DOWNLOAD_TWIN'
}

export const TWIN_CONFIG_ACTIONS = {
  GET_ALL_TWIN_CONFIGS: 'GET_ALL_TWIN_CONFIGS',
  ADD_TWIN_CONFIG: 'ADD_TWIN_CONFIG',
  UPDATE_TWIN_CONFIG: 'UPDATE_TWIN_CONFIG',
  CLEAR_TWIN_CONFIGS: 'CLEAR_TWIN_CONFIGS'
}

export const CONFIGURATION_ACTIONS = {
  CREATE_CONFIGURATION: 'CREATE_CONFIGURATION'
}

export const SOCKET_ACTIONS = {
  STORE_WS_DATA: 'STORE_WS_DATA'
}
