version: 0.2

env:
  variables:
    BUILD: true
    # AWS_PROFILE: ursaleo
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 257668213369
    AWS_EKS_NAME: ursaleo-eks
    NAMESPACE: dev
    HELM_EXPERIMENTAL_OCI: 1
      # VERSION: $(grep -E '"version"\s*:' package.json | sed 's/[^0-9.]//g')
    VERSION: '1.0.42'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # - npm install -g yarn
      - yarn install
      - yarn global add typescript

      
  pre_build:
    commands:
      - echo "Entering pre_build phase"
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod +x get_helm.sh
      - ./get_helm.sh
        # download sonar scanner
      - echo "Downloading Sonar Scanner"
      - export SONAR_SCANNER_VERSION=5.0.1.3006
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
     
  build:
    commands:
      - echo "yarn  build"
      - yarn run build-dev # Your React.js build command

  post_build:
    commands:

      - echo "Running Sonar Scanner (corrected format)"
      - sonar-scanner -X -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=$SONAR_ORG -Dsonar.host.url=https://sonarcloud.io -Dsonar.sources=. -Dsonar.login=$SONAR_TOKEN  # Assuming code is in the current directory
    
      - echo "start docker build"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ursaleo-portal-frontend:$VERSION -f Dockerfile .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ursaleo-portal-frontend:$VERSION
      - aws eks update-kubeconfig --region $AWS_REGION --name $AWS_EKS_NAME
      - helm upgrade --install --namespace $NAMESPACE --create-namespace --set image.tag=$VERSION --version "1.0.0" -f dev-helm-values.yaml ursaleo-portal-frontend oci://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/helm/ursaleo-portal
      - kubectl -n $NAMESPACE rollout restart deployment ursaleo-portal-frontend
      - kubectl get pod -n $NAMESPACE
      - echo "Frontend deployed"

# artifacts:
#   files:
#     - path/to/your/artifacts/directory/**/*
#   name: your-artifact-name

# cache:
#   paths:
#     - node_modules/**/*
#     - path/to/your/cache/directory/**/*
