version: 0.2

env:
  variables:
    BUILD: true
    # AWS_PROFILE: ursaleo
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 211125739464
    AWS_EKS_NAME: ursaleo-prod-eks
    NAMESPACE: prod
    HELM_EXPERIMENTAL_OCI: 1
      # VERSION: $(grep -E '"version"\s*:' package.json | sed 's/[^0-9.]//g')
    VERSION: '1.0.39'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      # - yarn install
      # - yarn global add typescript

      
  pre_build:
    commands:
      - echo "Entering pre_build phase"
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod +x get_helm.sh
      - ./get_helm.sh
     
  build:
    commands:
      - echo "npm  build"
      - npm run build-prod

  post_build:
    commands:

    
      - echo "start docker build"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ursaleo-portal-frontend-prod:VERSION -f Dockerfile .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ursaleo-portal-frontend-prod:$VERSION
      - aws eks update-kubeconfig --region $AWS_REGION --name $AWS_EKS_NAME
      - helm upgrade --install --namespace $NAMESPACE --create-namespace --set image.tag=$VERSION --version "1.0.0" -f prod-helm-values.yaml ursaleo-portal-frontend oci://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/helm/ursaleo-portal-prod
      - kubectl -n $NAMESPACE rollout restart deployment ursaleo-portal-frontend
      - kubectl get pod -n $NAMESPACE
      - echo "Frontend deployed"

# artifacts:
#   files:
#     - path/to/your/artifacts/directory/**/*
#   name: your-artifact-name

# cache:
#   paths:
#     - node_modules/**/*
#     - path/to/your/cache/directory/**/*
