replicaCount: 1

image:
  repository: 257668213369.dkr.ecr.us-east-1.amazonaws.com/ursaleo-portal-frontend
  tag: '1.0.42'
  pullPolicy: Always

fullnameOverride: 'ursaleo-portal-frontend'

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::257668213369:role/ursaleo-eks-dev-s3-role

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:257668213369:certificate/d940227f-9a2d-447a-b19f-b9bdc7d5618b
    alb.ingress.kubernetes.io/group.name: all
    alb.ingress.kubernetes.io/load-balancer-name: ursaleo-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-0b5f21ef9af9108fb
    alb.ingress.kubernetes.io/target-type: ip

  hosts:
    - host: dev.portal.ursaleo.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []

configMap:
  existing: []
  new:
    DOMAIN: dev.portal.ursaleo.com
    KEYCLOAK_AUTH_SERVER_URL: https://sso.portal.ursaleo.com
    KEYCLOAK_REALM_NAME: Ursaleo-Dev
  

secret:
  existing: []
  new:
    KEYCLOAK_CLIENT_ID: ursaleo-portal-frontend
    KEYCLOAK_CLIENT_SECRET: edc620af-2e5d-7221-6e02-6c09e8f2ed55

resources:
  requests:
    cpu: 20m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 1024Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80